version: '3.8'
services:
  nodeapp:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - reactapp

  reactapp:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./client:/usr/src/app
